DROP TABLE audit IF EXISTS CASCADE;
DROP TABLE geek_interet IF EXISTS CASCADE;
DROP TABLE geek IF EXISTS CASCADE;
DROP TABLE interet IF EXISTS CASCADE;
DROP TABLE type IF EXISTS CASCADE;

DROP SEQUENCE geek_seq IF EXISTS;
DROP SEQUENCE type_seq IF EXISTS;
DROP SEQUENCE interet_seq IF EXISTS;
DROP SEQUENCE audit_seq IF EXISTS;

CREATE TABLE geek (
	geekId	numeric not null,
	pseudo	varchar(50),
	nom		varchar(50),
	prenom	varchar(50),
	sexe	varchar(1),
	mail	varchar(100),
	dtnaiss	date,
	consult	numeric default 0,
	CONSTRAINT pk_geek PRIMARY KEY(geekId),
	CONSTRAINT uq_geek_pseudo UNIQUE(pseudo)
);

CREATE TABLE type (
	typeId	numeric not null,
	libelle	varchar(50),
	CONSTRAINT pk_type PRIMARY KEY(typeId)
);

CREATE TABLE interet (
	interetId	numeric not null,
	typeId		numeric not null,
	libelle		varchar(100),
	CONSTRAINT pk_interet PRIMARY KEY(interetId),
	CONSTRAINT fk_interet_type FOREIGN KEY(typeId) REFERENCES type(typeId)
);

CREATE TABLE geek_interet (
	geekId		numeric not null,
	interetId	numeric not null,
	CONSTRAINT pk_geekinteret PRIMARY KEY(geekId, interetId),
	CONSTRAINT fk_geekinteret_geek FOREIGN KEY(geekId) REFERENCES geek(geekId),
	CONSTRAINT fk_geekinteret_interet FOREIGN KEY(interetId) REFERENCES interet(interetId)
);

CREATE TABLE audit (
	auditId		numeric generated by default as identity(start with 1, increment by 1) not null,
	dateHeure	timestamp,
	ip			varchar(50),
	geekId		numeric not null,
	CONSTRAINT pk_audit PRIMARY KEY(auditId),
	CONSTRAINT fk_audit_geek FOREIGN KEY(geekId) REFERENCES geek(geekId)
);

CREATE SEQUENCE geek_seq START WITH 1;
CREATE SEQUENCE type_seq START WITH 1;
CREATE SEQUENCE interet_seq START WITH 1;
CREATE SEQUENCE audit_seq START WITH 1;